- hosts: localhost
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"
  become_method: sudo
  tasks:

  - name: Remove jack2
    become: yes
    become_user: root
    pacman:
      update_cache: yes
      state: removed
      force: yes
      name:
        - jack2

  - name: Install PipeWire
    become: yes
    become_user: root
    pacman:
      update_cache: yes
      extra_args: --ask yes
      name:
        - pipewire
        - pipewire-pulse
        - pipewire-jack
        - pipewire-alsa
        - helvum
        - carla

  - name: Enable PipeWire
    ansible.builtin.systemd:
      scope: user
      enabled: yes
      state: started
      name: pipewire

  - name: Enable PipeWire-pulse
    ansible.builtin.systemd:
      scope: user
      enabled: yes
      state: started
      name: pipewire-pulse

  - name: Install pavucontrol
    become: yes
    become_user: root
    pacman:
      update_cache: yes
      name:
        - pavucontrol

  - name: Install ardour
    become: yes
    become_user: root
    pacman:
      update_cache: yes
      name:
        - ardour

  - name: Install lmms
    become: yes
    become_user: root
    pacman:
      update_cache: yes
      name:
        - lmms

  - name: Install synths pacman
    become: yes
    become_user: root
    pacman:
      update_cache: yes
      name:
        - helm-synth
        - hydrogen
        - fluidsynth



  # - name: Install synths aur
  #   become: yes
  #   become_user: "{{ lookup('env', 'USER') }}"
  #   kewlfft.aur.aur:
  #     use: paru
  #     name:
  #       - xxxx

  - name: Install guitar plugins
    become: yes
    become_user: "{{ lookup('env', 'USER') }}"
    kewlfft.aur.aur:
      use: paru
      name:
        - guitarix
        # - tonelib-metal-bin
        # - tonelib-gfx-bin
        # - tonelib-jam-bin
        - tonelib-zoom-bin
        - tonelib-bass-drive-bin
        - tonelib-tube-warmth-bin
