---
- hosts: localhost
  roles:
  - kewlfft.aur
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"
  become_method: sudo
  tasks:

  - name: Install chromium browser
    become: yes
    become_user: root
    pacman:
      update_cache: yes
      name:
        - chromium

  - name: Install Meld
    become: yes
    become_user: root
    pacman:
      update_cache: yes
      name:
        - meld

  - name: Install Pritunl VPN
    become: yes
    become_user: "{{ lookup('env', 'USER') }}"
    aur:
      use: paru
      name:
        - pritunl-client-electron

  - name: Install Slack
    become: yes
    become_user: "{{ lookup('env', 'USER') }}"
    aur:
      use: paru
      name:
        - slack-desktop

  - name: Install Cisco VPN
    become: yes
    become_user: "{{ lookup('env', 'USER') }}"
    aur:
      use: paru
      name:
        - cisco-anyconnect
