- hosts: localhost
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"
  become_method: sudo
  tasks:

  - name: Install chromium browser
    become: yes
    become_user: root
    pacman:
      update_cache: yes
      name:
        - chromium

  - name: Install Meld
    become: yes
    become_user: root
    pacman:
      update_cache: yes
      name:
        - meld

  - name: Install Slack
    become: yes
    become_user: "{{ lookup('env', 'USER') }}"
    kewlfft.aur.aur:
      use: paru
      name:
        - slack-desktop

  - name: Install Cisco VPN
    become: yes
    become_user: "{{ lookup('env', 'USER') }}"
    kewlfft.aur.aur:
      use: paru
      name:
        - cisco-anyconnect

  - name: Prepare to install Pritunl
    become: yes
    shell:
      cmd: |
        sudo tee -a /etc/pacman.conf << EOF
        [pritunl]
        Server = https://repo.pritunl.com/stable/pacman
        EOF
        sudo pacman-key --keyserver hkp://keyserver.ubuntu.com -r 7568D9BB55FF9E5287D586017AE645C0CF8E292A
        sudo pacman-key --lsign-key 7568D9BB55FF9E5287D586017AE645C0CF8E292A
        sudo pacman -Sy

  - name: Install Pritunl VPN
    become: yes
    become_user: "{{ lookup('env', 'USER') }}"
    kewlfft.aur.aur:
      use: paru
      name:
        - pritunl-client-electron
