- name: Install Archlinux Music Dependencies
  hosts: localhost
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  become_method: sudo
  tasks:
    - name: Remove Jack2
      become: true
      become_user: root
      community.general.pacman:
        update_cache: true
        state: removed
        force: true
        name:
          - jack2

    - name: Install PipeWire
      become: true
      become_user: root
      community.general.pacman:
        update_cache: true
        extra_args: --ask yes
        name:
          - pipewire
          - pipewire-pulse
          - pipewire-jack
          - pipewire-alsa
          - helvum
          - carla

    - name: Enable PipeWire
      ansible.builtin.systemd:
        scope: user
        enabled: true
        state: started
        name: pipewire

    - name: Enable PipeWire-pulse
      ansible.builtin.systemd:
        scope: user
        enabled: true
        state: started
        name: pipewire-pulse

    - name: Install pavucontrol
      become: true
      become_user: root
      community.general.pacman:
        update_cache: true
        name:
          - pavucontrol

    - name: Install ardour
      become: true
      become_user: root
      community.general.pacman:
        update_cache: true
        name:
          - ardour

    - name: Install lmms
      become: true
      become_user: root
      community.general.pacman:
        update_cache: true
        name:
          - lmms

    - name: Install synths pacman
      become: true
      become_user: root
      community.general.pacman:
        update_cache: true
        name:
          - helm-synth
          - hydrogen
          - fluidsynth

    - name: Install guitar plugins
      become: true
      become_user: "{{ lookup('env', 'USER') }}"
      kewlfft.aur.aur:
        use: paru
        name:
          - guitarix
          # - tonelib-metal-bin
          # - tonelib-gfx-bin
          # - tonelib-jam-bin
          - tonelib-zoom-bin
          - tonelib-bass-drive-bin
          - tonelib-tube-warmth-bin
